objects/Account.object
<CustomObject>
    <fields>
        <fullName>Job_Number__c</fullName>
        <displayFormat>JN-{0000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>TECH_TechNode__c</fullName>
        <label>TECH_TechNode</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CORE_RedirecttoProspective.cls
public class CORE_RedirecttoProspective {
    @AuraEnabled
    public static String getRedirectToProspectURL(String accId) {
        /*String URL = 'https://jobcenter.prospective.ch/NJCWeb/services/fastinterface?';
        Account acc = [SELECT Id, Job_Number__c, Functional_Flag__c FROM Account WHERE Id=:accId LIMIT 1];
        Contact con = [SELECT Id,TECH_TechNode__c FROM Contact WHERE AccountId =:acc.Id LIMIT 1];
        
        if(acc.Functional_Flag__c && (con.TECH_TechNode__c!=NULL)){
            URL = URL + '&loginUrl='+con.TECH_TechNode__c+'&function=getAuftrag&kundeStelleId='+acc.Job_Number__c;
            return URL;
        }else if(!acc.Functional_Flag__c && (con.TECH_TechNode__c!=NULL)){
            URL = URL + '&loginUrl='+con.TECH_TechNode__c+'&function=getStellen';
            return URL;
        }else{
            return NULL;
        }*/
        return NULL;
    }
}