objects/Account_Platform_Event__e.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Account Platform Event</label>
    <pluralLabel>Account Platform Events</pluralLabel>
</CustomObject>

classes/AccountPlatformEventsHandler.cls
public class AccountPlatformEventsHandler {

    public static void afterUpdate(List<Account> newList){
        List<Account_Platform_Event__e> accPlatformEventList = new List<Account_Platform_Event__e>();
        for(Account acc : newList){
            Account_Platform_Event__e accEvent = new Account_Platform_Event__e();
            accEvent.Account_Name__c = acc.Name;
            accEvent.Phone__c = acc.Phone;
            accEvent.Salary__c = acc.AnnualRevenue;
            accPlatformEventList.add(accEvent);
        }

        if(!accPlatformEventList.isEmpty()){
            EventBus.publish(accPlatformEventList);
        }
    }
}