objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Event_Name__c</fullName>
        <label>Event Name</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BookingExtensionController.cls
public class BookingExtensionController {

    Booking__c booking;
    Event__c event;
    
    public BookingExtensionController (ApexPages.StandardController controller){
        booking= (Booking__c )controller.getRecord();
    }
    
    Public string myoutput{get;set;}
    
     Public static void MyMethode(){
        //myoutput = booking.Event_Name__c;
    }
    
    public PageReference mysave(){
        insert booking;
        PageReference pr = new PageReference ('/'+booking.id);
        return pr;
    }

}