objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Confirmed_Tickets__c</fullName>
        <label>Confirmed Tickets</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer Name</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Name__c</fullName>
        <label>Event Name</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Number_of_Tickets_Booked__c</fullName>
        <label>Number of Tickets Booked</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <label>Total Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Waiting_Tickets__c</fullName>
        <label>Waiting Tickets</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Concert__c.object
<CustomObject>
    <fields>
        <fullName>Concert_Name__c</fullName>
        <label>Concert Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Concert_Type__c</fullName>
        <label>Concert Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Premium</fullName>
                </value>
                <value>
                    <fullName>Regular</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Concert</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Concert ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Concerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Customer__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <externalId>true</externalId>
        <label>First Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <displayFormat>CUST-{0000}</displayFormat>
        <label>Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Avail_Tickets__c</fullName>
        <label>Available Tickets</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Concert__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Concert</label>
        <referenceTo>Concert__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Timing__c</fullName>
        <label>Event Timing</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Ticket_Price__c</fullName>
        <label>Ticket Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Tickets__c</fullName>
        <label>Total Tickets</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venue</label>
        <referenceTo>Venue__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Venue__c.object
<CustomObject>
    <fields>
        <fullName>Venue_Address__c</fullName>
        <label>Venue Address</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Venue_Name__c</fullName>
        <label>Venue Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Venue</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Venue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Venues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BookingSummaryController.cls
public class BookingSummaryController {
    
    public Event__c eventSummary{get; set;}
    public Customer__c custSummary{get; set;}
    public Venue__c venueSummary{get; set;}

    public Concert__c concertSummary{get; set;}
    
    public Booking__c bookSummary{get; set;}

    public Booking__c booking{ get; set; }
    public BookingSummaryController (){
   
        bookSummary = [Select Name, Customer_Name__c, Event_Name__c, Number_of_Tickets_Booked__c, Total_Price__c, Confirmed_Tickets__c, Waiting_Tickets__c
                        from Booking__c where ID=:ApexPages.currentPage().getParameters().get('id')];              
        eventSummary = [Select Avail_Tickets__c,Concert__c,Total_Tickets__c,Ticket_Price__c, Venue__c, Event_Timing__c
                      from Event__c 
                      where id = :bookSummary.Event_Name__c];
        concertSummary = [Select Concert_Type__c, Concert_Name__c from Concert__c where id = :eventSummary.Concert__c];
        custSummary = [Select First_Name__c,Last_Name__c,Email__c,Contact__c
                      from Customer__c 
                      where id = :bookSummary.Customer_Name__c];
        venueSummary = [Select Venue_Address__c, Venue_Name__c from Venue__c where id = :eventSummary.Venue__c];

    }
    
}