objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Confirmed_Tickets__c</fullName>
        <label>Confirmed Tickets</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Name__c</fullName>
        <label>Event Name</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Number_of_Tickets_Booked__c</fullName>
        <label>Number of Tickets Booked</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <label>Total Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Waiting_Tickets__c</fullName>
        <label>Waiting Tickets</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Concert__c.object
<CustomObject>
    <fields>
        <fullName>Concert_Name__c</fullName>
        <label>Concert Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Concert_Type__c</fullName>
        <label>Concert Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Premium</fullName>
                </value>
                <value>
                    <fullName>Regular</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Concert</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Concert ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Concerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Avail_Tickets__c</fullName>
        <label>Available Tickets</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Concert__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Concert</label>
        <referenceTo>Concert__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ticket_Price__c</fullName>
        <label>Ticket Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Tickets__c</fullName>
        <label>Total Tickets</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/NewBookingController.cls
public with sharing class NewBookingController {

    public NewBookingController(ApexPages.StandardController controller) {
        booking= (Booking__c)controller.getRecord();
    }

    public Event__c e{get; set;}
    public Concert__c c{get;set;}
    
    public Decimal updatedPrice{get; set;}
    public Decimal perTicketPrice;
    public Decimal availableTickets;
    
    public Booking__c booking{ get; set; }
    /*Exception Handling*/
        public virtual class BaseException extends Exception {}
        public class OtherException extends BaseException {}
    
    public NewBookingController (){
        booking = new Booking__c(); 
        
    }
    
    public void waitingBooking(){
        if(e.Avail_Tickets__c<=0 || booking.Number_of_Tickets_Booked__c>e.Avail_Tickets__c){
            e.Avail_Tickets__c = 0;
            update e;
        }else{               
            e.Avail_Tickets__c = e.Avail_Tickets__c - booking.Number_of_Tickets_Booked__c;
            update e;            
            
        }
    }

    
    public PageReference checkAvailability(){
       
        if(booking.Number_of_Tickets_Booked__c>e.Avail_Tickets__c && e.Avail_Tickets__c<=0){
            booking.Waiting_Tickets__c = booking.Number_of_Tickets_Booked__c;
            booking.Confirmed_Tickets__c = 0;
            PageReference pr = Page.WaitingPage;
            return pr;
        }else if(booking.Number_of_Tickets_Booked__c>e.Avail_Tickets__c){
            booking.Confirmed_Tickets__c = e.Avail_Tickets__c;
            booking.Waiting_Tickets__c = booking.Number_of_Tickets_Booked__c - e.Avail_Tickets__c;
            PageReference pr = Page.WaitingPage;
            return pr;
        }else{
            booking.Confirmed_Tickets__c = booking.Number_of_Tickets_Booked__c;
            booking.Waiting_Tickets__c = 0;
            PageReference pr = bookTickets();
            return pr;
        }
         
    }

   
    public PageReference  bookTickets(){          
        if(c.Concert_Type__c == 'Premium' && e.Avail_Tickets__c<= e.Total_Tickets__c * 0.10) {   
            //Premium Hike Booking
            PageReference pr = Page.PremiumIncreasedRatePage;
            updatedPrice  = getUpdatedPrice();
            return pr;
        }else if(c.Concert_Type__c == 'Premium' && e.Avail_Tickets__c<= e.Total_Tickets__c) {   
            //Premium Booking
            Decimal premiumTickets = 0;
            Decimal normalTickets = 0;
            //Premium Normal + Hike Booking
            if(e.Avail_Tickets__c-booking.Number_of_Tickets_Booked__c<=e.Total_Tickets__c *0.10){
                normalTickets = e.Avail_Tickets__c-(e.Total_Tickets__c*0.10);
                premiumTickets = booking.Number_of_Tickets_Booked__c-normalTickets ;
                updatedPrice  = (normalTickets *e.Ticket_Price__c)+(premiumTickets*e.Ticket_Price__c*1.1);
                PageReference pr = Page.PremiumIncreasedRatePage;
                return pr;
            }else{
                //Premium Normal
                booking.Total_Price__c = booking.Number_of_Tickets_Booked__c* e.Ticket_Price__c;  
                waitingBooking();
                insert booking;
                return new PageReference('/apex/NewBookingSummaryPage?id='+booking.id);
            }
        }else {
            //Regular Normal
            booking.Total_Price__c = booking.Number_of_Tickets_Booked__c* e.Ticket_Price__c;
            waitingBooking();
            insert booking;
            return new PageReference('/apex/NewBookingSummaryPage?id='+booking.id);
        }          
    }
    
     public PageReference  getBookingDetails(){
        e = [Select Avail_Tickets__c,Concert__c,Total_Tickets__c,Ticket_Price__c
                      from Event__c 
                      where id = :booking.Event_Name__c];
         perTicketPrice = e.Ticket_Price__c;
         availableTickets = e.Avail_Tickets__c;     
        
        c = [Select Concert_Type__c, Concert_Name__c from Concert__c where id = :e.Concert__c];
        PageReference pr = Page.BookingDetailsPage;

        return pr;
        
    }

    public Decimal getUpdatedPrice(){
        return booking.Number_of_Tickets_Booked__c* e.Ticket_Price__c*1.1;
    }
    
    public PageReference confirmBooking(){
        booking.Total_Price__c= updatedPrice;
        waitingBooking();
        insert booking;
        return new PageReference('/apex/NewBookingSummaryPage?id='+booking.id);
    }

    public PageReference cancelBooking(){
        PageReference pr = Page.PremiumCancelPage;
        return pr;
    }
    
    public PageReference goBack(){
        PageReference pr = Page.PremiumIncreasedRatePage;
        return pr;
    }
    
    public PageReference goToBookingList(){
        return new PageReference('/a0C/o');
    }
 
}