objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Buying_Group_Member__c</fullName>
        <label>Buying_Group Member</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ace Canada</fullName>
                </value>
                <value>
                    <fullName>BrandSource</fullName>
                </value>
                <value>
                    <fullName>Cantrex</fullName>
                </value>
                <value>
                    <fullName>Do-It-Best</fullName>
                </value>
                <value>
                    <fullName>Emery Jensen</fullName>
                </value>
                <value>
                    <fullName>Home Hardware</fullName>
                </value>
                <value>
                    <fullName>Loblaws</fullName>
                </value>
                <value>
                    <fullName>Mid States</fullName>
                </value>
                <value>
                    <fullName>Nationwide</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Orgil</fullName>
                </value>
                <value>
                    <fullName>Rona Canada</fullName>
                </value>
                <value>
                    <fullName>True Value</fullName>
                </value>
                <value>
                    <fullName>United Hardware</fullName>
                </value>
                <value>
                    <fullName>Wheat Belt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rebate_Period__c</fullName>
        <label>Rebate_Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Spring</fullName>
                </value>
                <value>
                    <fullName>Summer</fullName>
                </value>
                <value>
                    <fullName>Fall</fullName>
                </value>
                <value>
                    <fullName>Winter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submission_End_Date__c</fullName>
        <label>Submission_ End_Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Submission_Start_Date__c</fullName>
        <label>Submission_ Start_Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Dealer_Rebate</fullName>
        <active>true</active>
        <label>Dealer Rebate</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/Rebate_Item__c.object
<CustomObject>
    <fields>
        <fullName>Maximum_Rebate_Quantity__c</fullName>
        <label>Maximum_Rebate_Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rebate_Amount__c</fullName>
        <label>Rebate_Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Rebate_Item</label>
    <nameField>
        <displayFormat>RIN-{0000}</displayFormat>
        <label>Rebate_Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate_Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestDataFactory.cls
/*
* @Class		: TestDataFactory
* @Author		: 
* @Description	: This class will serve as a source for other Test Classes to create the data
* @CreatedDate  : 
*/
@isTest(SeeAllData=false)
public without sharing class TestDataFactory {

    /** 
    * ********************************************************
    * This method is to create test data for Campaign
    * ********************************************************
    */
    public static Campaign createCampaign(String buyingGroupMembers){
        Campaign testCampaign = new Campaign();
        testCampaign.Name = 'Test Campaign';
        testCampaign.RecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByDeveloperName().get('Dealer_Rebate').getRecordTypeId();
        testCampaign.Buying_Group_Member__c = buyingGroupMembers;
        testCampaign.Rebate_Period__c = 'Spring';
        testCampaign.StartDate = Date.today();
        testCampaign.EndDate = Date.today().addDays(30);
        testCampaign.Submission_Start_Date__c = Date.today();
        testCampaign.Submission_End_Date__c = Date.today().addDays(30);
        return testCampaign;
    }

    /** 
    * ********************************************************
    * This method is to create test data for Rebate_Item__c
    * ********************************************************
    */
    public static Rebate_Item__c createRebateItemWithoutCampaign(){
        Rebate_Item__c testRebateItem = new Rebate_Item__c();
        //testRebateItem.Name = 'Test Rebate Item';
        testRebateItem.Rebate_Amount__c = 4000;
        testRebateItem.Maximum_Rebate_Quantity__c = 40;
        return testRebateItem;
    }
    
}