objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Buying_Group_Member__c</fullName>
        <label>Buying_Group Member</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ace Canada</fullName>
                </value>
                <value>
                    <fullName>BrandSource</fullName>
                </value>
                <value>
                    <fullName>Cantrex</fullName>
                </value>
                <value>
                    <fullName>Do-It-Best</fullName>
                </value>
                <value>
                    <fullName>Emery Jensen</fullName>
                </value>
                <value>
                    <fullName>Home Hardware</fullName>
                </value>
                <value>
                    <fullName>Loblaws</fullName>
                </value>
                <value>
                    <fullName>Mid States</fullName>
                </value>
                <value>
                    <fullName>Nationwide</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Orgil</fullName>
                </value>
                <value>
                    <fullName>Rona Canada</fullName>
                </value>
                <value>
                    <fullName>True Value</fullName>
                </value>
                <value>
                    <fullName>United Hardware</fullName>
                </value>
                <value>
                    <fullName>Wheat Belt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submission_End_Date__c</fullName>
        <label>Submission_ End_Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Submission_Start_Date__c</fullName>
        <label>Submission_ Start_Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Dealer_Rebate</fullName>
        <active>true</active>
        <label>Dealer Rebate</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Final_Refund_Amount__c</fullName>
        <label>Final_Refund_Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GC1040</fullName>
                </value>
                <value>
                    <fullName>GC1060</fullName>
                </value>
                <value>
                    <fullName>GC3020</fullName>
                </value>
                <value>
                    <fullName>GC3040</fullName>
                </value>
                <value>
                    <fullName>GC3060</fullName>
                </value>
                <value>
                    <fullName>GC5020</fullName>
                </value>
                <value>
                    <fullName>GC5040</fullName>
                </value>
                <value>
                    <fullName>GC5060</fullName>
                </value>
                <value>
                    <fullName>GC1020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Refund_Request_Date__c</fullName>
        <label>Refund Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <summarizedField>CaseReplacementProduct__c.Subtotal__c</summarizedField>
        <summaryForeignKey>CaseReplacementProduct__c.Case__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <recordTypes>
        <fullName>RFC</fullName>
        <active>true</active>
        <businessProcess>RFC</businessProcess>
        <label>RFC</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/CaseReplacementProduct__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Replacement Products</relationshipLabel>
        <relationshipName>Case_Replacement_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <label>Product Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Case Replacement Products</relationshipLabel>
        <relationshipName>Case_Replacement_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Case Replacement Product</label>
    <nameField>
        <label>Case Replacement Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Replacement Products</pluralLabel>
    <recordTypes>
        <fullName>RFC</fullName>
        <active>true</active>
        <label>RFC</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Rebate_Item__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Rebate_Items</relationshipLabel>
        <relationshipName>Rebate_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Maximum_Rebate_Quantity__c</fullName>
        <label>Maximum_Rebate_Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <label>Product_Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Rebate_Items</relationshipLabel>
        <relationshipName>Rebate_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rebate_Amount__c</fullName>
        <label>Rebate_Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Rebate_Item</label>
    <nameField>
        <displayFormat>RIN-{0000}</displayFormat>
        <label>Rebate_Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rebate_Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RebateSubmissionService.cls
/*
 * @Class		: RebateSubmissionService
 * @Author		:
 * @Description	:
 * @CreatedDate  :
 */

public with sharing class RebateSubmissionService {
  public static final String DEALER_REBATE_CAMPAIGN = 'Dealer_Rebate';
  public static final String SALES_OPS_QUEUE = 'Sales_Ops';

  /*
    **********************************************************************************
    @Method Name    : fetchRelevantCampaigns
    @author         : 
    @description    : Method is used to fetch the relevant campaigns for the given Buying Group Member.
    @param          : buyingGroupMember
    @return         : List of Relevant Campaigns 
    **********************************************************************************
    */
  @AuraEnabled(cacheable=true)
  public static List<CampaignListWrapper> fetchRelevantCampaigns(
    String buyingGroupMembers
  ) {
    try {
      Date currentDate = Date.today();
      /**Creating a List of Buying Group Members*/
      List<String> buyingGroupMembersList = buyingGroupMembers.split(';');
      List<CampaignListWrapper> campaignWrapperList = new List<CampaignListWrapper>();
      List<Campaign> campaignList = [
        SELECT
          Id,
          Name,
          StartDate,
          EndDate,
          CurrencyISOCode,
          Submission_Start_Date__c,
          Submission_End_Date__c
        FROM Campaign
        WHERE
          RecordType.DeveloperName = :DEALER_REBATE_CAMPAIGN
          AND Buying_Group_Member__c IN :buyingGroupMembersList
          AND Submission_Start_Date__c <= :currentDate
          AND Submission_End_Date__c >= :currentDate
        ORDER BY Submission_Start_Date__c
      ];

      if (!campaignList.isEmpty()) {
        for (Campaign campaignItem : campaignList) {
          CampaignListWrapper campaignWrapper = new CampaignListWrapper();
          campaignWrapper.campaignId = campaignItem.Id;
          campaignWrapper.campaignName = campaignItem.Name;
          campaignWrapper.campaignStartDate = campaignItem.StartDate;
          campaignWrapper.campaignEndDate = campaignItem.EndDate;
          campaignWrapper.campaignSubmissionStartDate = campaignItem.Submission_Start_Date__c;
          campaignWrapper.campaignSubmissionEndDate = campaignItem.Submission_End_Date__c;
          campaignWrapperList.add(campaignWrapper);
        }
        return campaignWrapperList;
      }
      return null;
    } catch (Exception e) {
      throw new AuraHandledException('Error: ' + e.getMessage());
    }
  }

  /*
    **********************************************************************************
    @Method Name    : fetchRebateItemsByCampaignIds
    @author         : 
    @description    : Method is used to fetch rebate items associated with the given campaigns.
    @param          : campaignIdList
    @return         : List of Relevant Rebate Items with Campaign Record Values 
    **********************************************************************************
    */
  /**This method will be used for next screens*/
  @AuraEnabled(cacheable=true)
  public static List<RebateItemListWrapper> fetchRebateItemsByCampaignIds(
    List<Id> campaignIdList
  ) {
    try {
      //this query can be modified based on required fields we need to retrieve
      List<RebateItemListWrapper> rebateItemWrapperList = new List<RebateItemListWrapper>();
      List<Rebate_Item__c> rebateItemList = [
        SELECT
          Id,
          Name,
          Product__c,
          Product__r.Name,
          Product_Description__c,
          Maximum_Rebate_Quantity__c,
          Rebate_Amount__c,
          Campaign__r.CurrencyISOCode
        FROM Rebate_Item__c
        WHERE Campaign__c IN :campaignIdList
      ];
      if (!rebateItemList.isEmpty()) {
        for (Rebate_Item__c rebateItem : rebateItemList) {
          RebateItemListWrapper rebateItemWrapper = new RebateItemListWrapper();
          rebateItemWrapper.rebateItemId = rebateItem.Id;
          rebateItemWrapper.productId = rebateItem.Product__c;
          rebateItemWrapper.rebateItemSKU = rebateItem.Product__r?.Name;
          rebateItemWrapper.rebateItemDescription = rebateItem.Product_Description__c;
          rebateItemWrapper.maximumRebateQuantity = Integer.valueOf(
            rebateItem.Maximum_Rebate_Quantity__c
          );
          rebateItemWrapper.rebateAmount = rebateItem.Rebate_Amount__c;
          rebateItemWrapper.rebateQuantity = 0;
          rebateItemWrapper.campaignCurrency = rebateItem.Campaign__r.CurrencyISOCode;
          rebateItemWrapper.rebateItemProductId = rebateItem.Product__c;
          rebateItemWrapperList.add(rebateItemWrapper);
        }
        return rebateItemWrapperList;
      }
      return null;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  /*
    **********************************************************************************
    @Method Name    : createCaseWithCRP
    @author         : 
    @description    : Method is used to create RFC Case with Case Replacement Products.
    @param          : accId, accName, selectedCampaign, confirmedRI, finalRefundAmount
    @return         : 
    **********************************************************************************
    */
  /**This method will be used for next screens*/
  @AuraEnabled
  public static Boolean createCaseWithCRP(
    String accId,
    String accName,
    List<CampaignListWrapper> selectedCampaign,
    List<RebateItemListWrapper> confirmedRI,
    Decimal finalRefundAmount
  ) {
    try {
      Group salesOpsQueue = getSalesOpsQueue(SALES_OPS_QUEUE);
      /**Creating RFC Case Record */
      Case rFCCase = new Case();
      rFCCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName()
        .get('RFC')
        .getRecordTypeId();
      rFCCase.Subject = selectedCampaign[0]?.campaignName + ' - ' + accName;
      if (salesOpsQueue != null) {
        rFCCase.OwnerId = salesOpsQueue.Id;
      }
      rFCCase.AccountId = accId;
      rFCCase.Status = 'AR Review';
      rFCCase.Refund_Request_Date__c = System.today();
      rFCCase.Type = 'Discount';
      rFCCase.Final_Refund_Amount__c = finalRefundAmount;
      rFCCase.CurrencyIsoCode = confirmedRI != null
        ? confirmedRI[0].campaignCurrency
        : 'USD';
      Database.insert(rFCCase);
      /**Creating Related CRP Records */
      List<CaseReplacementProduct__c> cRPToBeInserted = new List<CaseReplacementProduct__c>();
      if (confirmedRI != null) {
        for (RebateItemListWrapper ri : confirmedRI) {
          CaseReplacementProduct__c cRP = new CaseReplacementProduct__c();
          cRP.Product__c = ri.productId;
          cRP.Unit_Price__c = ri.rebateAmount;
          cRP.Quantity__c = ri.rebateQuantity;
          cRP.Product_Description__c = ri.rebateItemDescription;
          //cRP.Total_Amount__c = ri.rebateAmount*ri.rebateQuantity;
          cRP.Case__c = rFCCase.Id;
          cRP.CurrencyISOCode = ri.campaignCurrency;
          cRPToBeInserted.add(cRP);
        }
        if (!cRPToBeInserted.isEmpty()) {
          Database.insert(cRPToBeInserted);
          return true;
        }
      }

      return null;
    } catch (Exception e) {
      throw new AuraHandledException('Error: ' + e.getMessage());
    }
  }

  /*
    **********************************************************************************
    @Method Name    : getSalesOpsQueue
    @author         : 
    @description    : Method is used to fetch the Sales_Ops Queue.
    @param          : queueName
    @return         : Sales_Ops Queue is present
    **********************************************************************************
    */
  public static Group getSalesOpsQueue(String queueName) {
    List<Group> salesOpsQueue = [
      SELECT Id, DeveloperName
      FROM Group
      WHERE Type = 'Queue' AND DeveloperName = :queueName
    ];
    if (salesOpsQueue != null && !salesOpsQueue.isEmpty()) {
      return salesOpsQueue[0];
    }
    return null;
  }

  /**This wrapper class will store field values related to Rebate Items*/
  public class CampaignListWrapper {
    @AuraEnabled
    public String campaignId { get; set; }
    @AuraEnabled
    public String campaignName { get; set; }
    @AuraEnabled
    public Date campaignStartDate { get; set; }
    @AuraEnabled
    public Date campaignEndDate { get; set; }
    @AuraEnabled
    public Date campaignSubmissionStartDate { get; set; }
    @AuraEnabled
    public Date campaignSubmissionEndDate { get; set; }
  }

  /**This wrapper class will store field values related to Rebate Items*/
  public class RebateItemListWrapper {
    @AuraEnabled
    public Id rebateItemId { get; set; }
    @AuraEnabled
    public Id productId { get; set; }
    @AuraEnabled
    public String rebateItemSKU { get; set; }
    @AuraEnabled
    public String rebateItemDescription { get; set; }
    @AuraEnabled
    public Integer maximumRebateQuantity { get; set; }
    @AuraEnabled
    public Double rebateAmount { get; set; }
    @AuraEnabled
    public Integer rebateQuantity { get; set; }
    @AuraEnabled
    public String campaignCurrency { get; set; }
    @AuraEnabled
    public Id rebateItemProductId { get; set; }
  }
}