objects/Candidate__c.object
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Position__c.object
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PCJController.cls
public class PCJController {
    public Position__c position;
    public Candidate__c candidate;
    Job_Application__c ja;
    
    public PCJController(){
        position = new Position__c();
        candidate = new Candidate__c();
    }
    
    public Position__c getPosition(){
        return position;
    }
    public Candidate__c getCandidate(){
        return candidate;
    }

    public PageReference save() {
        insert position;
        insert candidate;
        ja = new Job_Application__c();
        ja.position__c = position.id;
        ja.candidate__c = candidate.id;
        insert ja;
        return new PageReference('/'+ja.id);
    }


    public PageReference positioncandidatepage() {
        PageReference pr = Page.PositionCandidateDataPage;
        return pr;
    }

    public PageReference positionpage() {
        PageReference pr = Page.PositionDataPage;
        return pr;
    }

    public PageReference candidatepage() {
        PageReference pr = Page.CandidateDataPage;
        return pr;
    }

    
}