objects/Car__c.object
<CustomObject>
    <description>An object to store the Car information.</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hatchback</fullName>
                </value>
                <value>
                    <fullName>MUV</fullName>
                </value>
                <value>
                    <fullName>Sedan</fullName>
                </value>
                <value>
                    <fullName>SUV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MSRP__c</fullName>
        <label>MSRP</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <label>Make</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ford</fullName>
                </value>
                <value>
                    <fullName>Hyundai</fullName>
                </value>
                <value>
                    <fullName>Honda</fullName>
                </value>
                <value>
                    <fullName>Renault</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Picture_URL__c</fullName>
        <label>Picture URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CarController.cls
public with sharing class CarController {

    /**Wrapper */
    public class Filters{
        @AuraEnabled
        public String searchKey {get; set;}
        @AuraEnabled
        public Decimal maxPrice {get; set;}
        @AuraEnabled
        public String[] categories {get; set;}
        @AuraEnabled
        public String[] makeType {get; set;}
    }

    @AuraEnabled(cacheable=true)
    public static List<Car__c> getCars(Filters filters){
        try {
            String key, whereClause = '';
            Decimal maxPrice;
            String[] categories, makeType, criteria = new List<string>{};
            
            if(filters!=NULL){
                maxPrice = filters.maxPrice;
                categories = filters.categories;
                makeType = filters.makeType;
                if(!String.isEmpty(filters.searchKey)){
                    key = '%' + filters.searchKey + '%';
                    criteria.add('Name LIKE: key');
                }
                if(filters.maxPrice >= 0){
                    criteria.add('MSRP__c <= :maxPrice');
                }
                if(filters.categories != NULL){
                    criteria.add('Category__c IN :categories');
                }
                if(filters.makeType != NULL){
                    criteria.add('Make__c IN :makeType');
                }
                if(criteria.size()>0){
                    whereClause = 'WHERE ' + String.join(criteria, ' AND ');
                }
            }
            String query = 'SELECT Id, Name, MSRP__c, Description__c, Category__c, Make__c, Picture_URL__c FROM Car__c '+whereClause + ' WITH SECURITY_ENFORCED' + ' ORDER BY Name';
            return Database.query(query);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Car__c> getSimilarCars(Id carId, String[] makeType){
        try {
            return [SELECT Id, Name, MSRP__c, Category__c, 
                    Description__c, Picture_URL__c, Make__c FROM Car__c
                    WHERE Make__c IN : makeType AND Id != :carId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}