objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Job_Description__c</fullName>
        <label>Job Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestJobAppDetails.cls
@isTest
public class TestJobAppDetails {
	static ID jobid; 
    /*@testSetup
    private static void setJobAppData(){
        Position__c p = new Position__c(Name='P10', Job_Description__c='P10 Knowledge');
        insert p;
        
        Job_Application__c ja = new Job_Application__c();
        ja.Position__c = p.Id;
        insert ja;
        jobid = ja.id;
    }*/
    
	@isTest(seeAllData=true)
    private static void testGetJobApps(){
        JobAppDetails jad = new JobAppDetails();
        //List<Job_Application__c> jaList = jad.getJobApps();
        //System.assertEquals(1, jaList.size());
        //System.assert(jad.getJobApps().size()==1);
        System.assert(jad.getJobApps().size()==4);
        
    }
    
    @isTest
    private static void testUpdateJobApp(){
        Position__c p = new Position__c(Name='P12', Job_Description__c='P12 Knowledge');
        insert p;
        JobAppDetails jad = new JobAppDetails();
        jad.updateJobApp(jobid, p.id);
        
        Job_Application__c ja = [Select Name, Position__c
                                	from Job_Application__c
                                	where id=:jobid];
        //System.assert(ja.Position__c==p.id);
        
    }
}