objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Job_Description__c</fullName>
        <label>Job Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PositionEditor.cls
public class PositionEditor {
    Position__c position;
    public PositionEditor (){
        position = [Select Name, Job_Description__c, Status__c from Position__c
                        where ID=:ApexPages.currentPage().getParameters().get('id')];
    }
    public Position__c getPosition(){
        return position;
    }
    
    public PageReference edit() {
        update position;
        PageReference pr = new PageReference ('/'+position.id);
        return pr;
    }
    public PageReference mydelete() {
        delete position;
        //PageReference pr = new PageReference ('/'+position.id);
        return null;
    }

}