objects/Product_Quote__c.object
<CustomObject>
    <fields>
        <fullName>Gp__c</fullName>
        <label>Gp</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Product Quotes</relationshipLabel>
        <relationshipName>Product_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Cost__c</fullName>
        <label>Product Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_GP__c</fullName>
        <label>Product GP</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Selling_Price__c</fullName>
        <label>Selling Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Product Quote</label>
    <nameField>
        <label>Product Quotes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Quote__c.object
<CustomObject>
    <fields>
        <fullName>GP__c</fullName>
        <label>GP%</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Service Quotes</relationshipLabel>
        <relationshipName>Service_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selling_Price__c</fullName>
        <label>Selling Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Cost__c</fullName>
        <label>Service Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_GP__c</fullName>
        <label>Service GP</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Service Quote</label>
    <nameField>
        <displayFormat>SQ-{0000}</displayFormat>
        <label>Service Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/EditMargins.cls
public with sharing class EditMargins {
    
    @AuraEnabled(cacheable=true)
    public static List<Product_Quote__c> getProductQuotes(String oppId){
        try {
            return [SELECT Id, Product_Cost__c, Selling_Price__c, Gp__c, Product_GP__c FROM Product_Quote__c WHERE Opportunity__c =: oppId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Service_Quote__c> getSerivceQuotes(String oppId){
        try {
            return [SELECT Id, Service_Cost__c, Selling_Price__c, Gp__c, Service_GP__c FROM Service_Quote__c WHERE Opportunity__c =: oppId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}