objects/School__c.object
<CustomObject>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <label>Student Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>St-{0000}</displayFormat>
        <label>Student Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/StudentRestInboundService.cls
@RestResource(urlMapping='/studentsInfo/*')
global class StudentRestInboundService {

    global class StudentInfo{
        String studentName{get; set;}
        String studentAddress{get; set;}
        String studentPhone{get; set;}
        String schoolName{get; set;}
    }

    @HttpGet
    global static StudentInfo getStudent(){
        RestRequest request = RestContext.Request;

        String studentId = request.requestURI.subString(request.RequestURI.lastIndexOf('/')+1);

        Student__c studentRecord = [SELECT Id, Address__c, Student_Name__c, Phone_Number__c, School__r.Name 
                                    FROM Student__c
                                    WHERE Id =: studentId];

        StudentInfo studentWrapper = new StudentInfo();
        studentWrapper.studentName = studentRecord.Student_Name__c;
        studentWrapper.studentAddress = studentRecord.Address__c;
        studentWrapper.studentPhone = studentRecord.Phone_Number__c;
        studentWrapper.schoolName = studentRecord.School__r.Name;

        // Account acc = new Account();
        // acc.Name = 'Trying to create Account from HTTPGET request';
        // Database.insert(acc);

        return studentWrapper;

    }
}